import type { LineageRow, SourceDefinition } from "./types";

/**
 * Governed registry of every information source the GBI model is allowed to
 * cite. Numbers in the demo UI are still synthetic; this registry is the
 * contract for *where* a production bank should read each field, and what
 * the monthly GitHub Action actually probes.
 */
export const SOURCE_REGISTRY: SourceDefinition[] = [
  {
    id: "shaparak-monthly",
    name: "گزارش اقتصادی ماهانه شاپرک",
    owner: "شرکت شبکه الکترونیکی پرداخت کارت (شاپرک)",
    kind: "official",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 12,
    urls: {
      primary: "https://www.shaparak.ir",
      mirrors: ["https://shaparak.ir"],
    },
    fields: ["گردش شبکه پرداخت", "تعداد تراکنش", "تعداد ابزار پذیرش", "سهم کارتخوان"],
    usedFor: ["زمینه کلان گردش پرداخت", "تقویم انتشار ماهانه اصناف"],
    screens: ["میز کار", "منابع اطلاعاتی"],
    licenseNote: "گزارش عمومی شاپرک؛ نقل با ذکر منبع.",
    howWeUse:
      "پس از انتشار گزارش ماه، جاب GitHub صفحه رسمی را واکشی می‌کند، اثرانگشت محتوا را ذخیره می‌کند و دوره پوشش را جلو می‌برد. ارقام نمونه داشبورد از این فایل جایگزین نمی‌شوند مگر در حالت بانک واقعی.",
    limitation:
      "سایت شاپرک API عمومی پایدار ندارد و اغلب به‌صورت PDF منتشر می‌شود؛ از رانرهای خارج از ایران ممکن است در دسترس نباشد.",
  },
  {
    id: "shaparak-terms",
    name: "اصطلاحات و تعریف پذیرنده شاپرک",
    owner: "شرکت شاپرک",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.shaparak.ir/docs/terms",
    },
    fields: ["تعریف پذیرنده", "ابزار پذیرش", "طبقه‌بندی شبکه"],
    usedFor: ["واژه‌نامه", "محدوده ماتریس BCG (غیررسمی بودن طبقه‌بندی)"],
    screens: ["ماتریس اصناف", "منابع اطلاعاتی"],
    licenseNote: "مستند عمومی اصطلاحات شاپرک.",
    howWeUse: "مرجع معنایی واژه‌های پذیرنده و پایانه؛ هیچ رقم KPI از این صفحه خوانده نمی‌شود.",
    limitation: "استاندارد رسمی «ماتریس BCG اصناف» در این سند وجود ندارد.",
  },
  {
    id: "shaparak-mcc",
    name: "کد MCC رسته پذیرنده",
    owner: "شاپرک / استاندارد کارت‌پرداخت",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.shaparak.ir",
    },
    fields: ["defaultMcc"],
    usedFor: ["اتصال رسته شغلی به شبکه پذیرندگی"],
    screens: ["ماتریس اصناف", "ماشین‌حساب"],
    licenseNote: "کد چهاررقمی متعارف پذیرندگی.",
    howWeUse: "هر رسته در طبقه‌بندی داخلی یک MCC پیش‌فرض دارد تا به سوییچ پذیرندگی نگاشت شود.",
    limitation: "نگاشت نمونه است؛ بانک باید جدول MCC قرارداد PSP خود را جایگزین کند.",
  },
  {
    id: "cbi-pos-fee",
    name: "پلکان کارمزد خرید کارتی بانک مرکزی",
    owner: "بانک مرکزی جمهوری اسلامی ایران",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.cbi.ir",
      mirrors: ["https://cbi.ir"],
    },
    fields: [
      "کارمزد ثابت تراکنش خرد",
      "آستانه ۶ میلیون ریال",
      "نرخ ۰٫۰۲٪",
      "سقف ۴۰ هزار ریال",
    ],
    usedFor: ["موتور Π-Bank", "ماشین‌حساب", "ماتریس BCG"],
    screens: ["ماشین‌حساب", "میز کار", "ماتریس اصناف"],
    licenseNote: "بخشنامه عمومی کارمزد؛ باید با ابلاغیه جاری تطبیق شود.",
    howWeUse:
      "فرمول کارمزد مدل دقیقاً همان پلکان اعلام‌شده است و در کاتالوگ به‌صورت فرض نسخه‌بندی‌شده ذخیره می‌شود. تغییر بخشنامه → هشدار بازبینی انسانی.",
    limitation: "سهم بانک/PSP/پذیرنده در قرارداد ممکن است با سقف اعلامی متفاوت باشد.",
  },
  {
    id: "cbi-reserve-lending",
    name: "نرخ تسهیلات و نسبت سپرده قانونی",
    owner: "بانک مرکزی جمهوری اسلامی ایران",
    kind: "model",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.cbi.ir",
    },
    fields: ["lendingRate", "reserveRatio"],
    usedFor: ["ارزش‌گذاری ماهانه رسوب CASA"],
    screens: ["میز کار", "ماشین‌حساب"],
    licenseNote: "مفروض مدل خزانه‌داری؛ نه نرخ قطعی هر بانک.",
    howWeUse: "حاشیه رسوب = مانده × (نرخ تسهیلات − سپرده قانونی) ÷ ۱۲. مقادیر پیش‌فرض ۲۳٪ و ۱۳٪ هستند.",
    limitation: "نرخ تمام‌شده منابع هر بانک متفاوت است و باید از خزانه‌داری خوانده شود.",
  },
  {
    id: "inta-coefficients",
    name: "ضرایب اینتاکد و تبصره ماده ۱۰۰",
    owner: "سازمان امور مالیاتی کشور",
    kind: "official",
    cadence: "annual",
    lagDaysAfterMonthEnd: 20,
    annualMonth: 2,
    urls: {
      primary: "https://www.intamedia.ir",
      mirrors: ["https://tax.gov.ir"],
    },
    fields: ["intaCode", "intaProfitRatio"],
    usedFor: ["شناسه فعالیت مالیاتی رسته", "ضریب سود تبصره ۱۰۰"],
    screens: ["ماتریس اصناف", "ماشین‌حساب"],
    licenseNote: "جداول عمومی ضرایب سود فعالیت.",
    howWeUse:
      "هر رسته یک اینتاکد و ضریب سود دارد. جاب سالانه (اوایل سال) تغییر صفحه را تشخیص می‌دهد و پرچم بازبینی انسانی می‌زند؛ ضریب را خودکار جایگزین نمی‌کند.",
    limitation: "ضرایب معمولاً سالانه است نه ماهانه؛ ارقام فعلی نمونه آموزشی‌اند.",
  },
  {
    id: "isic-amar",
    name: "طبقه‌بندی استاندارد فعالیت‌های اقتصادی (ISIC)",
    owner: "مرکز آمار ایران / نظام طبقه‌بندی بین‌المللی",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.amar.org.ir",
    },
    fields: ["isicCode", "isicCodePrefix"],
    usedFor: ["گروه‌بندی تولیدی / توزیعی / خدماتی"],
    screens: ["ماتریس اصناف"],
    licenseNote: "طبقه‌بندی عمومی فعالیت اقتصادی.",
    howWeUse: "کد ISIC رسته را به گروه اصلی صنف وصل می‌کند.",
    limitation: "نسخه ISIC مورد استفاده بانک باید با پرونده مالیاتی هم‌خوان باشد.",
  },
  {
    id: "chamber-guilds",
    name: "رسته‌بندی اتاق اصناف ایران",
    owner: "اتاق اصناف ایران",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.iranianasnaf.ir",
    },
    fields: ["عنوان رسته شغلی", "گروه صنفی"],
    usedFor: ["نام‌گذاری رسته‌ها در ماتریس"],
    screens: ["ماتریس اصناف"],
    licenseNote: "طبقه‌بندی صنفی عمومی.",
    howWeUse: "عنوان رسته‌ها با ادبیات اتاق اصناف هم‌خوان شده است تا شعبه همان زبانی را ببیند که جواز کسب دارد.",
    limitation: "اتاق استانی ممکن است زیررسته محلی داشته باشد که در نمونه نیست.",
  },
  {
    id: "tax-moodian",
    name: "سامانه مؤدیان (اتصال پایانه)",
    owner: "سازمان امور مالیاتی کشور",
    kind: "official",
    cadence: "continuous",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://my.tax.gov.ir",
      mirrors: ["https://tax.gov.ir"],
    },
    fields: ["isTaxCompliant"],
    usedFor: ["امتیاز انطباق ۲۰٪", "قفل اعتبار در صورت عدم اتصال"],
    screens: ["میز کار", "سرنخ‌ها", "ماشین‌حساب"],
    licenseNote: "وضعیت اتصال مودی؛ داده حساس.",
    howWeUse: "در حالت بانک واقعی از استعلام اتصال پایانه به سامانه مؤدیان خوانده می‌شود. در دمو به‌صورت پرچم نمونه است.",
    limitation: "این سامانه لاگین می‌خواهد و از GitHub واکشی نمی‌شود.",
  },
  {
    id: "bank-internal-pos",
    name: "پایش ماهانه پایانه و تراکنش شعبه",
    owner: "هسته بانکی / سوئیچ PSP طرف قرارداد",
    kind: "internal",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 3,
    urls: {
      primary: "internal://bank/pos-metrics",
    },
    fields: [
      "monthlyTxCount",
      "monthlyTxVolume",
      "posTerminalCount",
      "acquiringFeeEarned",
      "operatingSupportCost",
    ],
    usedFor: ["KPI میز کار", "رتبه رسته‌ها", "امتیاز سرنخ"],
    screens: ["میز کار", "ماتریس اصناف", "سرنخ‌ها", "ماشین‌حساب"],
    licenseNote: "داده اختصاصی بانک؛ در حالت استاتیک با corpus نمونه جایگزین شده است.",
    howWeUse:
      "پس از بستن ماه (حدود روز ۳ ماه بعد) باید از انبار داده بانک وارد شود. در GitHub Pages به‌جایش داده دترمینیستیک شش‌ماهه جلالی تولید می‌شود.",
    limitation: "بدون DATABASE_URL هیچ رقم واقعی شعبه وارد سامانه نمی‌شود.",
  },
  {
    id: "bank-casa-float",
    name: "مانده روزانه حساب جاری پذیرنده (CASA)",
    owner: "هسته سپرده‌ای بانک",
    kind: "internal",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 2,
    urls: {
      primary: "internal://bank/casa-float",
    },
    fields: ["avgDailyFloatBalance"],
    usedFor: ["بازده رسوب", "سقف تسهیلات"],
    screens: ["میز کار", "ماشین‌حساب"],
    licenseNote: "داده اختصاصی بانک.",
    howWeUse: "میانگین مانده روزانه حساب جاری در دوره گزارش.",
    limitation: "در دمو از الگوی رسته (تراکنش × سبد × روز ماندگاری) ساخته می‌شود.",
  },
  {
    id: "shaparak-news-mirror",
    name: "آینه خبری کشف انتشار گزارش شاپرک",
    owner: "رسانه‌های تخصصی پرداخت (راه پرداخت و مشابه)",
    kind: "mirror",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 10,
    urls: {
      primary: "https://way2pay.ir",
      mirrors: ["https://peivast.com"],
    },
    fields: ["سیگنال «گزارش شاپرک منتشر شد»"],
    usedFor: ["تقویم انتشار؛ نه ورود رقم به مدل"],
    screens: ["منابع اطلاعاتی"],
    licenseNote: "خبر؛ منبع آماری محسوب نمی‌شود.",
    howWeUse:
      "اگر سایت شاپرک از رانر GitHub در دسترس نباشد، تغییر عنوان/هش آینه‌های خبری فقط زنگ «احتمالاً گزارش جدید آمده» می‌زند.",
    limitation: "هیچ عددی از آینه خبری وارد KPI یا ماشین‌حساب نمی‌شود.",
  },
];

export const SOURCE_BY_ID = new Map(SOURCE_REGISTRY.map((source) => [source.id, source]));

/** Which UI number comes from which source — shown on the sources page. */
export const FIELD_LINEAGE: LineageRow[] = [
  {
    field: "totals.totalTxVolume",
    label: "گردش ماهانه تراکنش",
    screens: ["میز کار"],
    origin: "sample",
    sourceIds: ["bank-internal-pos", "shaparak-monthly"],
    note: "در دمو از corpus نمونه؛ در بانک از سوئیچ پایانه. گزارش شاپرک فقط زمینه کلان است.",
  },
  {
    field: "totals.totalFloat",
    label: "رسوب تجمیعی CASA",
    screens: ["میز کار"],
    origin: "sample",
    sourceIds: ["bank-casa-float"],
    note: "میانگین مانده روزانه حساب جاری — فقط از هسته بانک قابل اتکا است.",
  },
  {
    field: "totals.monthlyFloatYield",
    label: "بازده ماهانه رسوب",
    screens: ["میز کار", "ماشین‌حساب"],
    origin: "model",
    sourceIds: ["cbi-reserve-lending", "bank-casa-float"],
    note: "فرمول مدل: مانده × (نرخ تسهیلات − سپرده قانونی) ÷ ۱۲.",
  },
  {
    field: "cbiPosFee",
    label: "کارمزد هر تراکنش کارتخوان",
    screens: ["ماشین‌حساب", "ماتریس اصناف"],
    origin: "model",
    sourceIds: ["cbi-pos-fee"],
    note: "پلکان بانک مرکزی به‌صورت فرض نسخه‌بندی‌شده در موتور است.",
  },
  {
    field: "subGuild.intaProfitRatio",
    label: "ضریب سود اینتاکد",
    screens: ["ماتریس اصناف"],
    origin: "sample",
    sourceIds: ["inta-coefficients"],
    note: "ساختار فیلد رسمی است؛ عدد فعلی نمونه آموزشی است و با جدول سالانه سازمان مالیاتی جایگزین می‌شود.",
  },
  {
    field: "subGuild.isicCode",
    label: "کد ISIC رسته",
    screens: ["ماتریس اصناف"],
    origin: "sample",
    sourceIds: ["isic-amar", "chamber-guilds"],
    note: "کد طبقه‌بندی فعالیت؛ با جواز کسب و پرونده مالیاتی باید یکی باشد.",
  },
  {
    field: "subGuild.defaultMcc",
    label: "کد MCC شاپرک",
    screens: ["ماتریس اصناف"],
    origin: "sample",
    sourceIds: ["shaparak-mcc"],
    note: "نگاشت رسته به پذیرندگی؛ جدول عملیاتی از PSP/شاپرک می‌آید.",
  },
  {
    field: "merchant.isTaxCompliant",
    label: "اتصال به سامانه مؤدیان",
    screens: ["سرنخ‌ها", "میز کار", "ماشین‌حساب"],
    origin: "sample",
    sourceIds: ["tax-moodian"],
    note: "در دمو پرچم نمونه است؛ در بانک باید از استعلام رسمی خوانده شود.",
  },
  {
    field: "leadScore",
    label: "امتیاز سرنخ",
    screens: ["سرنخ‌ها", "ماشین‌حساب"],
    origin: "model",
    sourceIds: ["bank-casa-float", "bank-internal-pos", "tax-moodian"],
    note: "ترکیب وزنی رسوب ۳۵٪ + گردش ۲۵٪ + تناسب اعتباری ۲۰٪ + مالیات ۲۰٪.",
  },
  {
    field: "bcgMatrix",
    label: "ماتریس بوستون رسته‌ها",
    screens: ["ماتریس اصناف"],
    origin: "model",
    sourceIds: ["bank-internal-pos", "cbi-pos-fee", "cbi-reserve-lending", "shaparak-terms"],
    note: "تصمیم‌یار داخلی است نه استاندارد شاپرک. محورها از گردش داخلی و کارمزد مدل ساخته می‌شوند.",
  },
];
