import type { LineageRow, SourceDefinition } from "./types";

/**
 * Governed registry of every information source the GBI model is allowed to
 * cite. Dashboard KPIs are published Shaparak/CBI/INTA aggregates; named
 * merchants and CASA remain internal-only gaps. This is also the contract
 * the monthly GitHub Action probes.
 */
export const SOURCE_REGISTRY: SourceDefinition[] = [
  {
    id: "shaparak-monthly",
    name: "گزارش اقتصادی ماهانه شاپرک",
    owner: "شرکت شبکه الکترونیکی پرداخت کارت (شاپرک)",
    kind: "official",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 12,
    urls: {
      primary: "https://www.shaparak.ir",
      mirrors: ["https://shaparak.ir"],
    },
    fields: ["گردش شبکه پرداخت", "تعداد تراکنش", "تعداد ابزار پذیرش", "سهم کارتخوان"],
    usedFor: ["زمینه کلان گردش پرداخت", "تقویم انتشار ماهانه اصناف"],
    screens: ["میز کار", "منابع اطلاعاتی"],
    licenseNote: "گزارش عمومی شاپرک؛ نقل با ذکر منبع.",
    howWeUse:
      "KPI میز کار (گردش، تعداد، ترکیب ابزار مرداد ۱۴۰۵) از بازتاب گزارش اقتصادی شاپرک با ذکر منبع پر می‌شود. جاب GitHub صفحه رسمی را واکشی می‌کند؛ اگر PDF از رانر نرسد، ارقام نقل‌شدهٔ همین corpus باقی می‌ماند و اثرانگشت unreachable ثبت می‌شود.",
    limitation:
      "سایت شاپرک API عمومی پایدار ندارد و اغلب به‌صورت PDF منتشر می‌شود؛ از رانرهای خارج از ایران ممکن است در دسترس نباشد. تفکیک رسته/MCC و فهرست پذیرنده در گزارش عمومی نیست.",
  },
  {
    id: "shaparak-terms",
    name: "اصطلاحات و تعریف پذیرنده شاپرک",
    owner: "شرکت شاپرک",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.shaparak.ir/docs/terms",
    },
    fields: ["تعریف پذیرنده", "ابزار پذیرش", "طبقه‌بندی شبکه"],
    usedFor: ["واژه‌نامه", "تعریف پذیرنده و ابزار پذیرش"],
    screens: ["اطلس رسته‌ها", "منابع اطلاعاتی"],
    licenseNote: "مستند عمومی اصطلاحات شاپرک.",
    howWeUse: "مرجع معنایی واژه‌های پذیرنده و پایانه؛ هیچ رقم KPI از این صفحه خوانده نمی‌شود.",
    limitation: "استاندارد رسمی «ماتریس BCG اصناف» در این سند وجود ندارد.",
  },
  {
    id: "shaparak-mcc",
    name: "کد MCC رسته پذیرنده",
    owner: "شاپرک / استاندارد کارت‌پرداخت",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.shaparak.ir",
    },
    fields: ["defaultMcc"],
    usedFor: ["اتصال رسته شغلی به شبکه پذیرندگی"],
    screens: ["اطلس رسته‌ها"],
    licenseNote: "کد چهاررقمی متعارف پذیرندگی.",
    howWeUse: "هر رسته در طبقه‌بندی داخلی یک MCC پیش‌فرض دارد تا به سوییچ پذیرندگی نگاشت شود.",
    limitation: "MCC رسته‌ها از استاندارد پذیرندگی است نه از فایل ماهانه شاپرک؛ جدول عملیاتی PSP بانک باید جایگزین شود.",
  },
  {
    id: "cbi-pos-fee",
    name: "پلکان کارمزد خرید کارتی بانک مرکزی",
    owner: "بانک مرکزی جمهوری اسلامی ایران",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.cbi.ir",
      mirrors: ["https://cbi.ir"],
    },
    fields: [
      "کارمزد ثابت تراکنش خرد",
      "آستانه ۶ میلیون ریال",
      "نرخ ۰٫۰۲٪",
      "سقف ۴۰ هزار ریال",
    ],
    usedFor: ["موتور Π-Bank", "ماشین‌حساب کارمزد"],
    screens: ["ماشین‌حساب"],
    licenseNote: "بخشنامه عمومی کارمزد؛ باید با ابلاغیه جاری تطبیق شود.",
    howWeUse:
      "فرمول کارمزد مدل دقیقاً همان پلکان اعلام‌شده است و در کاتالوگ به‌صورت فرض نسخه‌بندی‌شده ذخیره می‌شود. تغییر بخشنامه → هشدار بازبینی انسانی.",
    limitation: "نانوایی و سوپرمارکت معاف‌اند و بانک پذیرنده می‌پردازد. سهم بانک/PSP در قرارداد ممکن است با سقف اعلامی متفاوت باشد.",
  },
  {
    id: "cbi-reserve-lending",
    name: "نرخ تسهیلات و نسبت سپرده قانونی",
    owner: "بانک مرکزی جمهوری اسلامی ایران",
    kind: "model",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.cbi.ir",
    },
    fields: ["lendingRate", "reserveRatio"],
    usedFor: ["فرض نرخ در موتور — در UI استاتیک نمایش داده نمی‌شود"],
    screens: ["منابع اطلاعاتی"],
    licenseNote: "مفروض مدل خزانه‌داری؛ نه نرخ قطعی هر بانک.",
    howWeUse: "حاشیه رسوب = مانده × (نرخ تسهیلات − سپرده قانونی) ÷ ۱۲. مقادیر پیش‌فرض ۲۳٪ و ۱۳٪ هستند.",
    limitation: "نرخ تمام‌شده منابع هر بانک متفاوت است و باید از خزانه‌داری خوانده شود.",
  },
  {
    id: "inta-coefficients",
    name: "ضرایب اینتاکد و تبصره ماده ۱۰۰",
    owner: "سازمان امور مالیاتی کشور",
    kind: "official",
    cadence: "annual",
    lagDaysAfterMonthEnd: 20,
    annualMonth: 2,
    urls: {
      primary: "https://www.intamedia.ir",
      mirrors: ["https://tax.gov.ir"],
    },
    fields: ["intaCode", "intaProfitRatio"],
    usedFor: ["شناسه فعالیت مالیاتی رسته", "ضریب سود تبصره ۱۰۰"],
    screens: ["اطلس رسته‌ها", "ماشین‌حساب"],
    licenseNote: "جداول عمومی ضرایب سود فعالیت.",
    howWeUse:
      "هر رسته یک اینتاکد و ضریب سود دارد. جاب سالانه (اوایل سال) تغییر صفحه را تشخیص می‌دهد و پرچم بازبینی انسانی می‌زند؛ ضریب را خودکار جایگزین نمی‌کند.",
    limitation: "فقط ضرایبی که در جدول عمومی نقل شده‌اند وارد شده‌اند (سوپرمارکت ۸٫۵٪، رستوران معمولی ۱۴٪، اغذیه ۱۵–۲۰٪). بقیه رسته‌ها خالی‌اند نه inventشده.",
  },
  {
    id: "isic-amar",
    name: "طبقه‌بندی استاندارد فعالیت‌های اقتصادی (ISIC)",
    owner: "مرکز آمار ایران / نظام طبقه‌بندی بین‌المللی",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.amar.org.ir",
    },
    fields: ["isicCode", "isicCodePrefix"],
    usedFor: ["گروه‌بندی تولیدی / توزیعی / خدماتی"],
    screens: ["اطلس رسته‌ها"],
    licenseNote: "طبقه‌بندی عمومی فعالیت اقتصادی.",
    howWeUse: "کد ISIC رسته را به گروه اصلی صنف وصل می‌کند.",
    limitation: "نسخه ISIC مورد استفاده بانک باید با پرونده مالیاتی هم‌خوان باشد.",
  },
  {
    id: "chamber-guilds",
    name: "رسته‌بندی اتاق اصناف ایران",
    owner: "اتاق اصناف ایران",
    kind: "official",
    cadence: "on-change",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://www.iranianasnaf.ir",
    },
    fields: ["عنوان رسته شغلی", "گروه صنفی"],
    usedFor: ["نام‌گذاری رسته‌ها در اطلس"],
    screens: ["اطلس رسته‌ها"],
    licenseNote: "طبقه‌بندی صنفی عمومی.",
    howWeUse: "عنوان رسته‌ها با ادبیات اتاق اصناف هم‌خوان شده است تا شعبه همان زبانی را ببیند که جواز کسب دارد.",
    limitation: "اتاق استانی ممکن است زیررسته محلی داشته باشد که در نمونه نیست.",
  },
  {
    id: "tax-moodian",
    name: "سامانه مؤدیان (اتصال پایانه)",
    owner: "سازمان امور مالیاتی کشور",
    kind: "official",
    cadence: "continuous",
    lagDaysAfterMonthEnd: 0,
    urls: {
      primary: "https://my.tax.gov.ir",
      mirrors: ["https://tax.gov.ir"],
    },
    fields: ["isTaxCompliant"],
    usedFor: ["وضعیت اتصال مالیاتی — در UI استاتیک نمایش داده نمی‌شود"],
    screens: ["منابع اطلاعاتی"],
    licenseNote: "وضعیت اتصال مودی؛ داده حساس.",
    howWeUse: "در حالت بانک واقعی از استعلام اتصال پایانه به سامانه مؤدیان خوانده می‌شود. در حالت استاتیک پرچم کمپین رسته است نه وضعیت یک فروشگاه حقیقی.",
    limitation: "این سامانه لاگین می‌خواهد و از GitHub واکشی نمی‌شود.",
  },
  {
    id: "bank-internal-pos",
    name: "پایش ماهانه پایانه و تراکنش شعبه",
    owner: "هسته بانکی / سوئیچ PSP طرف قرارداد",
    kind: "internal",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 3,
    urls: {
      primary: "internal://bank/pos-metrics",
    },
    fields: [
      "monthlyTxCount",
      "monthlyTxVolume",
      "posTerminalCount",
      "acquiringFeeEarned",
      "operatingSupportCost",
    ],
    usedFor: ["پایش شعبه — در UI استاتیک نیست؛ میز کار جمع شاپرک را نشان می‌دهد"],
    screens: ["منابع اطلاعاتی"],
    licenseNote: "داده اختصاصی بانک؛ در حالت استاتیک با جمع شبکه شاپرک جایگزین شده نه با پرونده شعبه.",
    howWeUse:
      "پس از بستن ماه باید از انبار داده بانک وارد شود. در GitHub Pages به‌جایش جمع ماهنامه شاپرک نمایش داده می‌شود — نه تراکنش شعبه.",
    limitation: "بدون DATABASE_URL هیچ رقم واقعی شعبه وارد سامانه نمی‌شود.",
  },
  {
    id: "bank-casa-float",
    name: "مانده روزانه حساب جاری پذیرنده (CASA)",
    owner: "هسته سپرده‌ای بانک",
    kind: "internal",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 2,
    urls: {
      primary: "internal://bank/casa-float",
    },
    fields: ["avgDailyFloatBalance"],
    usedFor: ["بازده رسوب — در UI استاتیک نمایش داده نمی‌شود"],
    screens: ["منابع اطلاعاتی"],
    licenseNote: "داده اختصاصی بانک.",
    howWeUse: "میانگین مانده روزانه حساب جاری در دوره گزارش.",
    limitation: "در حالت استاتیک نمایش داده نمی‌شود؛ ساختن رسوب از روی الگوی رسته حذف شد.",
  },
  {
    id: "shaparak-news-mirror",
    name: "آینه خبری کشف انتشار گزارش شاپرک",
    owner: "رسانه‌های تخصصی پرداخت (راه پرداخت و مشابه)",
    kind: "mirror",
    cadence: "monthly",
    lagDaysAfterMonthEnd: 10,
    urls: {
      primary: "https://www.ecoiran.com",
      mirrors: ["https://banker.ir", "https://way2pay.ir"],
    },
    fields: ["بازتاب گزارش اقتصادی شاپرک"],
    usedFor: ["خواندن ارقام ماهنامه وقتی PDF شاپرک از رانر نرسد"],
    screens: ["منابع اطلاعاتی", "میز کار"],
    licenseNote: "خبر؛ منبع آماری مستقل نیست — فقط نقل گزارش شاپرک.",
    howWeUse:
      "بازتاب EcoIran و banker.ir متن گزارش اقتصادی شاپرک را نقل می‌کند. KPI به شماره گزارش شاپرک استناد می‌شود نه به خبر به عنوان منبع مستقل. واحد «همت» در خبرها گاهی غلط است و با چند بازتاب کنترل می‌شود.",
    limitation: "خبر می‌تواند واحد را اشتباه کند؛ رقم وارد مدل نمی‌شود مگر با سازگاری MoM/YoY و ذکر شماره گزارش.",
  },
];

export const SOURCE_BY_ID = new Map(SOURCE_REGISTRY.map((source) => [source.id, source]));

/** Which UI number comes from which source — shown on the sources page. */
export const FIELD_LINEAGE: LineageRow[] = [
  {
    field: "totals.volume",
    label: "گردش ماهانه شبکه شاپرک",
    screens: ["میز کار"],
    origin: "official",
    sourceIds: ["shaparak-monthly"],
    note: "جمع گزارش اقتصادی شاپرک (آخرین ماه نقل‌شده: مرداد ۱۴۰۵ / گزارش ۱۳۴).",
  },
  {
    field: "totals.txCount",
    label: "تعداد تراکنش شبکه",
    screens: ["میز کار"],
    origin: "official",
    sourceIds: ["shaparak-monthly"],
    note: "تعداد نقل‌شده همان ماهنامه؛ برای تیر از MoM مرداد گرد شده است.",
  },
  {
    field: "instruments",
    label: "ترکیب ابزار پذیرش مرداد",
    screens: ["میز کار"],
    origin: "official",
    sourceIds: ["shaparak-monthly", "shaparak-news-mirror"],
    note: "کارتخوان و اینترنت رقم اعلامی مرداد ۱۴۰۵؛ سایر ابزار مانده پس از این دو است.",
  },
  {
    field: "posBasket",
    label: "سبد اعلامی کارتخوان",
    screens: ["میز کار", "ماشین‌حساب"],
    origin: "official",
    sourceIds: ["shaparak-monthly"],
    note: "حدود ۶۹۴ هزار تومان در بازتاب گزارش مرداد ۱۴۰۵.",
  },
  {
    field: "mellatShare",
    label: "سهم بانک ملت به‌عنوان پذیرنده",
    screens: ["میز کار"],
    origin: "official",
    sourceIds: ["shaparak-monthly", "shaparak-news-mirror"],
    note: "۱۸٫۷۹٪ تعداد و ۱۹٫۹۵٪ مبلغ در مرداد ۱۴۰۵.",
  },
  {
    field: "ticketGap",
    label: "فاصله رشد مبلغ و تعداد مرداد",
    screens: ["میز کار"],
    origin: "model",
    sourceIds: ["shaparak-monthly"],
    note: "تفریق دو درصد نقل‌شده MoM (۷٫۲۶ − ۲٫۹۷). منبع تازه نیست.",
  },
  {
    field: "instrumentBasket",
    label: "سبد ابزار (اعلامی یا تقسیم)",
    screens: ["میز کار"],
    origin: "model",
    sourceIds: ["shaparak-monthly"],
    note: "کارتخوان رقم اعلامی ۶۹۴ هزار تومان است. اینترنت و سایر حاصل تقسیم مبلغ÷تعداد همان ماه‌اند.",
  },
  {
    field: "mellatImplied",
    label: "حاصل‌ضرب سهم ملت در جمع شبکه",
    screens: ["میز کار"],
    origin: "model",
    sourceIds: ["shaparak-monthly", "shaparak-news-mirror"],
    note: "شاپرک رقم مطلق ملت را جدا نداده؛ این ضرب سهم اعلامی در جمع شبکه است.",
  },
  {
    field: "cbiPosFee",
    label: "کارمزد هر تراکنش کارتخوان",
    screens: ["ماشین‌حساب"],
    origin: "model",
    sourceIds: ["cbi-pos-fee"],
    note: "پلکان بانک مرکزی به‌صورت فرض نسخه‌بندی‌شده؛ فقط در ماشین‌حساب سناریو.",
  },
  {
    field: "subGuild.intaProfitRatio",
    label: "ضریب سود اینتاکد",
    screens: ["اطلس رسته‌ها"],
    origin: "official",
    sourceIds: ["inta-coefficients"],
    note: "فقط رسته‌هایی که ضریب‌شان در جدول عمومی نقل شده پر شده‌اند؛ بقیه خالی‌اند.",
  },
  {
    field: "subGuild.isicCode",
    label: "کد ISIC رسته",
    screens: ["اطلس رسته‌ها"],
    origin: "official",
    sourceIds: ["isic-amar", "chamber-guilds"],
    note: "کد طبقه‌بندی فعالیت اقتصادی؛ با جواز کسب و پرونده مالیاتی باید یکی باشد.",
  },
  {
    field: "subGuild.defaultMcc",
    label: "کد MCC شاپرک",
    screens: ["اطلس رسته‌ها"],
    origin: "official",
    sourceIds: ["shaparak-mcc"],
    note: "کد چهاررقمی متعارف پذیرندگی؛ جدول قرارداد PSP بانک مقدم است.",
  },
];
